name: TODO -> GH issues

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Converts todos into issues
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0